//package src.RevEngEntities;
//// Generated Mar 21, 2020 5:51:12 PM by Hibernate Tools 5.2.3.Final
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import static javax.persistence.GenerationType.IDENTITY;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.Table;
//
///**
// * TablesDet generated by hbm2java
// */
//@Entity
//@Table(name = "tables_det", catalog = "sql_db")
//public class TablesDet implements java.io.Serializable {
//
//	private Integer id;
//	private Tables tables;
//	private String name;
//	private String displayName;
//	private String showInList;
//	private String showInDetail;
//	private String dataType;
//
//	public TablesDet() {
//	}
//
//	public TablesDet(Tables tables, String name, String showInList, String showInDetail) {
//		this.tables = tables;
//		this.name = name;
//		this.showInList = showInList;
//		this.showInDetail = showInDetail;
//	}
//
//	public TablesDet(Tables tables, String name, String displayName, String showInList, String showInDetail,
//			String dataType) {
//		this.tables = tables;
//		this.name = name;
//		this.displayName = displayName;
//		this.showInList = showInList;
//		this.showInDetail = showInDetail;
//		this.dataType = dataType;
//	}
//
//	@Id
//	@GeneratedValue(strategy = IDENTITY)
//
//	@Column(name = "ID", unique = true, nullable = false)
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "TABLE_ID", nullable = false)
//	public Tables getTables() {
//		return this.tables;
//	}
//
//	public void setTables(Tables tables) {
//		this.tables = tables;
//	}
//
//	@Column(name = "NAME", nullable = false, length = 100)
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	@Column(name = "DISPLAY_NAME", length = 100)
//	public String getDisplayName() {
//		return this.displayName;
//	}
//
//	public void setDisplayName(String displayName) {
//		this.displayName = displayName;
//	}
//
//	@Column(name = "SHOW_IN_LIST", nullable = false, length = 1)
//	public String getShowInList() {
//		return this.showInList;
//	}
//
//	public void setShowInList(String showInList) {
//		this.showInList = showInList;
//	}
//
//	@Column(name = "SHOW_IN_DETAIL", nullable = false, length = 1)
//	public String getShowInDetail() {
//		return this.showInDetail;
//	}
//
//	public void setShowInDetail(String showInDetail) {
//		this.showInDetail = showInDetail;
//	}
//
//	@Column(name = "DATA_TYPE", length = 1)
//	public String getDataType() {
//		return this.dataType;
//	}
//
//	public void setDataType(String dataType) {
//		this.dataType = dataType;
//	}
//
//}
