//package src.RevEngEntities;
//// Generated Mar 21, 2020 5:51:12 PM by Hibernate Tools 5.2.3.Final
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.GeneratedValue;
//import static javax.persistence.GenerationType.IDENTITY;
//import javax.persistence.Id;
//import javax.persistence.Table;
//
///**
// * Users generated by hbm2java
// */
//@Entity
//@Table(name = "users", catalog = "sql_db")
//public class Users implements java.io.Serializable {
//
//	private Integer id;
//	private String name;
//	private String userName;
//	private String password;
//
//	public Users() {
//	}
//
//	public Users(String name, String userName, String password) {
//		this.name = name;
//		this.userName = userName;
//		this.password = password;
//	}
//
//	@Id
//	@GeneratedValue(strategy = IDENTITY)
//
//	@Column(name = "ID", unique = true, nullable = false)
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	@Column(name = "NAME", nullable = false, length = 100)
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	@Column(name = "USER_NAME", nullable = false, length = 50)
//	public String getUserName() {
//		return this.userName;
//	}
//
//	public void setUserName(String userName) {
//		this.userName = userName;
//	}
//
//	@Column(name = "PASSWORD", nullable = false, length = 50)
//	public String getPassword() {
//		return this.password;
//	}
//
//	public void setPassword(String password) {
//		this.password = password;
//	}
//
//}
