//package src.RevEngEntities;
//// Generated Mar 21, 2020 5:51:12 PM by Hibernate Tools 5.2.3.Final
//
//import java.math.BigDecimal;
//import javax.persistence.Column;
//import javax.persistence.Embeddable;
//
///**
// * UserId generated by hbm2java
// */
//@Embeddable
//public class UserId implements java.io.Serializable {
//
//	private String host;
//	private String user;
//	private String password;
//	private String selectPriv;
//	private String insertPriv;
//	private String updatePriv;
//	private String deletePriv;
//	private String createPriv;
//	private String dropPriv;
//	private String reloadPriv;
//	private String shutdownPriv;
//	private String processPriv;
//	private String filePriv;
//	private String grantPriv;
//	private String referencesPriv;
//	private String indexPriv;
//	private String alterPriv;
//	private String showDbPriv;
//	private String superPriv;
//	private String createTmpTablePriv;
//	private String lockTablesPriv;
//	private String executePriv;
//	private String replSlavePriv;
//	private String replClientPriv;
//	private String createViewPriv;
//	private String showViewPriv;
//	private String createRoutinePriv;
//	private String alterRoutinePriv;
//	private String createUserPriv;
//	private String eventPriv;
//	private String triggerPriv;
//	private String createTablespacePriv;
//	private String deleteHistoryPriv;
//	private String sslType;
//	private String sslCipher;
//	private String x509Issuer;
//	private String x509Subject;
//	private long maxQuestions;
//	private long maxUpdates;
//	private long maxConnections;
//	private long maxUserConnections;
//	private String plugin;
//	private String authenticationString;
//	private String passwordExpired;
//	private String isRole;
//	private String defaultRole;
//	private BigDecimal maxStatementTime;
//
//	public UserId() {
//	}
//
//	public UserId(String host, String user, String sslCipher, String x509Issuer, String x509Subject, long maxQuestions,
//			long maxUpdates, long maxConnections, long maxUserConnections, String plugin, String authenticationString,
//			String passwordExpired, String defaultRole, BigDecimal maxStatementTime) {
//		this.host = host;
//		this.user = user;
//		this.sslCipher = sslCipher;
//		this.x509Issuer = x509Issuer;
//		this.x509Subject = x509Subject;
//		this.maxQuestions = maxQuestions;
//		this.maxUpdates = maxUpdates;
//		this.maxConnections = maxConnections;
//		this.maxUserConnections = maxUserConnections;
//		this.plugin = plugin;
//		this.authenticationString = authenticationString;
//		this.passwordExpired = passwordExpired;
//		this.defaultRole = defaultRole;
//		this.maxStatementTime = maxStatementTime;
//	}
//
//	public UserId(String host, String user, String password, String selectPriv, String insertPriv, String updatePriv,
//			String deletePriv, String createPriv, String dropPriv, String reloadPriv, String shutdownPriv,
//			String processPriv, String filePriv, String grantPriv, String referencesPriv, String indexPriv,
//			String alterPriv, String showDbPriv, String superPriv, String createTmpTablePriv, String lockTablesPriv,
//			String executePriv, String replSlavePriv, String replClientPriv, String createViewPriv, String showViewPriv,
//			String createRoutinePriv, String alterRoutinePriv, String createUserPriv, String eventPriv,
//			String triggerPriv, String createTablespacePriv, String deleteHistoryPriv, String sslType, String sslCipher,
//			String x509Issuer, String x509Subject, long maxQuestions, long maxUpdates, long maxConnections,
//			long maxUserConnections, String plugin, String authenticationString, String passwordExpired, String isRole,
//			String defaultRole, BigDecimal maxStatementTime) {
//		this.host = host;
//		this.user = user;
//		this.password = password;
//		this.selectPriv = selectPriv;
//		this.insertPriv = insertPriv;
//		this.updatePriv = updatePriv;
//		this.deletePriv = deletePriv;
//		this.createPriv = createPriv;
//		this.dropPriv = dropPriv;
//		this.reloadPriv = reloadPriv;
//		this.shutdownPriv = shutdownPriv;
//		this.processPriv = processPriv;
//		this.filePriv = filePriv;
//		this.grantPriv = grantPriv;
//		this.referencesPriv = referencesPriv;
//		this.indexPriv = indexPriv;
//		this.alterPriv = alterPriv;
//		this.showDbPriv = showDbPriv;
//		this.superPriv = superPriv;
//		this.createTmpTablePriv = createTmpTablePriv;
//		this.lockTablesPriv = lockTablesPriv;
//		this.executePriv = executePriv;
//		this.replSlavePriv = replSlavePriv;
//		this.replClientPriv = replClientPriv;
//		this.createViewPriv = createViewPriv;
//		this.showViewPriv = showViewPriv;
//		this.createRoutinePriv = createRoutinePriv;
//		this.alterRoutinePriv = alterRoutinePriv;
//		this.createUserPriv = createUserPriv;
//		this.eventPriv = eventPriv;
//		this.triggerPriv = triggerPriv;
//		this.createTablespacePriv = createTablespacePriv;
//		this.deleteHistoryPriv = deleteHistoryPriv;
//		this.sslType = sslType;
//		this.sslCipher = sslCipher;
//		this.x509Issuer = x509Issuer;
//		this.x509Subject = x509Subject;
//		this.maxQuestions = maxQuestions;
//		this.maxUpdates = maxUpdates;
//		this.maxConnections = maxConnections;
//		this.maxUserConnections = maxUserConnections;
//		this.plugin = plugin;
//		this.authenticationString = authenticationString;
//		this.passwordExpired = passwordExpired;
//		this.isRole = isRole;
//		this.defaultRole = defaultRole;
//		this.maxStatementTime = maxStatementTime;
//	}
//
//	@Column(name = "Host", nullable = false, length = 60)
//	public String getHost() {
//		return this.host;
//	}
//
//	public void setHost(String host) {
//		this.host = host;
//	}
//
//	@Column(name = "User", nullable = false, length = 80)
//	public String getUser() {
//		return this.user;
//	}
//
//	public void setUser(String user) {
//		this.user = user;
//	}
//
//	@Column(name = "Password")
//	public String getPassword() {
//		return this.password;
//	}
//
//	public void setPassword(String password) {
//		this.password = password;
//	}
//
//	@Column(name = "Select_priv", length = 1)
//	public String getSelectPriv() {
//		return this.selectPriv;
//	}
//
//	public void setSelectPriv(String selectPriv) {
//		this.selectPriv = selectPriv;
//	}
//
//	@Column(name = "Insert_priv", length = 1)
//	public String getInsertPriv() {
//		return this.insertPriv;
//	}
//
//	public void setInsertPriv(String insertPriv) {
//		this.insertPriv = insertPriv;
//	}
//
//	@Column(name = "Update_priv", length = 1)
//	public String getUpdatePriv() {
//		return this.updatePriv;
//	}
//
//	public void setUpdatePriv(String updatePriv) {
//		this.updatePriv = updatePriv;
//	}
//
//	@Column(name = "Delete_priv", length = 1)
//	public String getDeletePriv() {
//		return this.deletePriv;
//	}
//
//	public void setDeletePriv(String deletePriv) {
//		this.deletePriv = deletePriv;
//	}
//
//	@Column(name = "Create_priv", length = 1)
//	public String getCreatePriv() {
//		return this.createPriv;
//	}
//
//	public void setCreatePriv(String createPriv) {
//		this.createPriv = createPriv;
//	}
//
//	@Column(name = "Drop_priv", length = 1)
//	public String getDropPriv() {
//		return this.dropPriv;
//	}
//
//	public void setDropPriv(String dropPriv) {
//		this.dropPriv = dropPriv;
//	}
//
//	@Column(name = "Reload_priv", length = 1)
//	public String getReloadPriv() {
//		return this.reloadPriv;
//	}
//
//	public void setReloadPriv(String reloadPriv) {
//		this.reloadPriv = reloadPriv;
//	}
//
//	@Column(name = "Shutdown_priv", length = 1)
//	public String getShutdownPriv() {
//		return this.shutdownPriv;
//	}
//
//	public void setShutdownPriv(String shutdownPriv) {
//		this.shutdownPriv = shutdownPriv;
//	}
//
//	@Column(name = "Process_priv", length = 1)
//	public String getProcessPriv() {
//		return this.processPriv;
//	}
//
//	public void setProcessPriv(String processPriv) {
//		this.processPriv = processPriv;
//	}
//
//	@Column(name = "File_priv", length = 1)
//	public String getFilePriv() {
//		return this.filePriv;
//	}
//
//	public void setFilePriv(String filePriv) {
//		this.filePriv = filePriv;
//	}
//
//	@Column(name = "Grant_priv", length = 1)
//	public String getGrantPriv() {
//		return this.grantPriv;
//	}
//
//	public void setGrantPriv(String grantPriv) {
//		this.grantPriv = grantPriv;
//	}
//
//	@Column(name = "References_priv", length = 1)
//	public String getReferencesPriv() {
//		return this.referencesPriv;
//	}
//
//	public void setReferencesPriv(String referencesPriv) {
//		this.referencesPriv = referencesPriv;
//	}
//
//	@Column(name = "Index_priv", length = 1)
//	public String getIndexPriv() {
//		return this.indexPriv;
//	}
//
//	public void setIndexPriv(String indexPriv) {
//		this.indexPriv = indexPriv;
//	}
//
//	@Column(name = "Alter_priv", length = 1)
//	public String getAlterPriv() {
//		return this.alterPriv;
//	}
//
//	public void setAlterPriv(String alterPriv) {
//		this.alterPriv = alterPriv;
//	}
//
//	@Column(name = "Show_db_priv", length = 1)
//	public String getShowDbPriv() {
//		return this.showDbPriv;
//	}
//
//	public void setShowDbPriv(String showDbPriv) {
//		this.showDbPriv = showDbPriv;
//	}
//
//	@Column(name = "Super_priv", length = 1)
//	public String getSuperPriv() {
//		return this.superPriv;
//	}
//
//	public void setSuperPriv(String superPriv) {
//		this.superPriv = superPriv;
//	}
//
//	@Column(name = "Create_tmp_table_priv", length = 1)
//	public String getCreateTmpTablePriv() {
//		return this.createTmpTablePriv;
//	}
//
//	public void setCreateTmpTablePriv(String createTmpTablePriv) {
//		this.createTmpTablePriv = createTmpTablePriv;
//	}
//
//	@Column(name = "Lock_tables_priv", length = 1)
//	public String getLockTablesPriv() {
//		return this.lockTablesPriv;
//	}
//
//	public void setLockTablesPriv(String lockTablesPriv) {
//		this.lockTablesPriv = lockTablesPriv;
//	}
//
//	@Column(name = "Execute_priv", length = 1)
//	public String getExecutePriv() {
//		return this.executePriv;
//	}
//
//	public void setExecutePriv(String executePriv) {
//		this.executePriv = executePriv;
//	}
//
//	@Column(name = "Repl_slave_priv", length = 1)
//	public String getReplSlavePriv() {
//		return this.replSlavePriv;
//	}
//
//	public void setReplSlavePriv(String replSlavePriv) {
//		this.replSlavePriv = replSlavePriv;
//	}
//
//	@Column(name = "Repl_client_priv", length = 1)
//	public String getReplClientPriv() {
//		return this.replClientPriv;
//	}
//
//	public void setReplClientPriv(String replClientPriv) {
//		this.replClientPriv = replClientPriv;
//	}
//
//	@Column(name = "Create_view_priv", length = 1)
//	public String getCreateViewPriv() {
//		return this.createViewPriv;
//	}
//
//	public void setCreateViewPriv(String createViewPriv) {
//		this.createViewPriv = createViewPriv;
//	}
//
//	@Column(name = "Show_view_priv", length = 1)
//	public String getShowViewPriv() {
//		return this.showViewPriv;
//	}
//
//	public void setShowViewPriv(String showViewPriv) {
//		this.showViewPriv = showViewPriv;
//	}
//
//	@Column(name = "Create_routine_priv", length = 1)
//	public String getCreateRoutinePriv() {
//		return this.createRoutinePriv;
//	}
//
//	public void setCreateRoutinePriv(String createRoutinePriv) {
//		this.createRoutinePriv = createRoutinePriv;
//	}
//
//	@Column(name = "Alter_routine_priv", length = 1)
//	public String getAlterRoutinePriv() {
//		return this.alterRoutinePriv;
//	}
//
//	public void setAlterRoutinePriv(String alterRoutinePriv) {
//		this.alterRoutinePriv = alterRoutinePriv;
//	}
//
//	@Column(name = "Create_user_priv", length = 1)
//	public String getCreateUserPriv() {
//		return this.createUserPriv;
//	}
//
//	public void setCreateUserPriv(String createUserPriv) {
//		this.createUserPriv = createUserPriv;
//	}
//
//	@Column(name = "Event_priv", length = 1)
//	public String getEventPriv() {
//		return this.eventPriv;
//	}
//
//	public void setEventPriv(String eventPriv) {
//		this.eventPriv = eventPriv;
//	}
//
//	@Column(name = "Trigger_priv", length = 1)
//	public String getTriggerPriv() {
//		return this.triggerPriv;
//	}
//
//	public void setTriggerPriv(String triggerPriv) {
//		this.triggerPriv = triggerPriv;
//	}
//
//	@Column(name = "Create_tablespace_priv", length = 1)
//	public String getCreateTablespacePriv() {
//		return this.createTablespacePriv;
//	}
//
//	public void setCreateTablespacePriv(String createTablespacePriv) {
//		this.createTablespacePriv = createTablespacePriv;
//	}
//
//	@Column(name = "Delete_history_priv", length = 1)
//	public String getDeleteHistoryPriv() {
//		return this.deleteHistoryPriv;
//	}
//
//	public void setDeleteHistoryPriv(String deleteHistoryPriv) {
//		this.deleteHistoryPriv = deleteHistoryPriv;
//	}
//
//	@Column(name = "ssl_type", length = 9)
//	public String getSslType() {
//		return this.sslType;
//	}
//
//	public void setSslType(String sslType) {
//		this.sslType = sslType;
//	}
//
//	@Column(name = "ssl_cipher", nullable = false)
//	public String getSslCipher() {
//		return this.sslCipher;
//	}
//
//	public void setSslCipher(String sslCipher) {
//		this.sslCipher = sslCipher;
//	}
//
//	@Column(name = "x509_issuer", nullable = false)
//	public String getX509Issuer() {
//		return this.x509Issuer;
//	}
//
//	public void setX509Issuer(String x509Issuer) {
//		this.x509Issuer = x509Issuer;
//	}
//
//	@Column(name = "x509_subject", nullable = false)
//	public String getX509Subject() {
//		return this.x509Subject;
//	}
//
//	public void setX509Subject(String x509Subject) {
//		this.x509Subject = x509Subject;
//	}
//
//	@Column(name = "max_questions", nullable = false)
//	public long getMaxQuestions() {
//		return this.maxQuestions;
//	}
//
//	public void setMaxQuestions(long maxQuestions) {
//		this.maxQuestions = maxQuestions;
//	}
//
//	@Column(name = "max_updates", nullable = false)
//	public long getMaxUpdates() {
//		return this.maxUpdates;
//	}
//
//	public void setMaxUpdates(long maxUpdates) {
//		this.maxUpdates = maxUpdates;
//	}
//
//	@Column(name = "max_connections", nullable = false)
//	public long getMaxConnections() {
//		return this.maxConnections;
//	}
//
//	public void setMaxConnections(long maxConnections) {
//		this.maxConnections = maxConnections;
//	}
//
//	@Column(name = "max_user_connections", nullable = false)
//	public long getMaxUserConnections() {
//		return this.maxUserConnections;
//	}
//
//	public void setMaxUserConnections(long maxUserConnections) {
//		this.maxUserConnections = maxUserConnections;
//	}
//
//	@Column(name = "plugin", nullable = false)
//	public String getPlugin() {
//		return this.plugin;
//	}
//
//	public void setPlugin(String plugin) {
//		this.plugin = plugin;
//	}
//
//	@Column(name = "authentication_string", nullable = false)
//	public String getAuthenticationString() {
//		return this.authenticationString;
//	}
//
//	public void setAuthenticationString(String authenticationString) {
//		this.authenticationString = authenticationString;
//	}
//
//	@Column(name = "password_expired", nullable = false, length = 1)
//	public String getPasswordExpired() {
//		return this.passwordExpired;
//	}
//
//	public void setPasswordExpired(String passwordExpired) {
//		this.passwordExpired = passwordExpired;
//	}
//
//	@Column(name = "is_role", length = 1)
//	public String getIsRole() {
//		return this.isRole;
//	}
//
//	public void setIsRole(String isRole) {
//		this.isRole = isRole;
//	}
//
//	@Column(name = "default_role", nullable = false)
//	public String getDefaultRole() {
//		return this.defaultRole;
//	}
//
//	public void setDefaultRole(String defaultRole) {
//		this.defaultRole = defaultRole;
//	}
//
//	@Column(name = "max_statement_time", nullable = false, precision = 12, scale = 6)
//	public BigDecimal getMaxStatementTime() {
//		return this.maxStatementTime;
//	}
//
//	public void setMaxStatementTime(BigDecimal maxStatementTime) {
//		this.maxStatementTime = maxStatementTime;
//	}
//
//	public boolean equals(Object other) {
//		if ((this == other))
//			return true;
//		if ((other == null))
//			return false;
//		if (!(other instanceof UserId))
//			return false;
//		UserId castOther = (UserId) other;
//
//		return ((this.getHost() == castOther.getHost()) || (this.getHost() != null && castOther.getHost() != null
//				&& this.getHost().equals(castOther.getHost())))
//				&& ((this.getUser() == castOther.getUser()) || (this.getUser() != null && castOther.getUser() != null
//						&& this.getUser().equals(castOther.getUser())))
//				&& ((this.getPassword() == castOther.getPassword()) || (this.getPassword() != null
//						&& castOther.getPassword() != null && this.getPassword().equals(castOther.getPassword())))
//				&& ((this.getSelectPriv() == castOther.getSelectPriv()) || (this.getSelectPriv() != null
//						&& castOther.getSelectPriv() != null && this.getSelectPriv().equals(castOther.getSelectPriv())))
//				&& ((this.getInsertPriv() == castOther.getInsertPriv()) || (this.getInsertPriv() != null
//						&& castOther.getInsertPriv() != null && this.getInsertPriv().equals(castOther.getInsertPriv())))
//				&& ((this.getUpdatePriv() == castOther.getUpdatePriv()) || (this.getUpdatePriv() != null
//						&& castOther.getUpdatePriv() != null && this.getUpdatePriv().equals(castOther.getUpdatePriv())))
//				&& ((this.getDeletePriv() == castOther.getDeletePriv()) || (this.getDeletePriv() != null
//						&& castOther.getDeletePriv() != null && this.getDeletePriv().equals(castOther.getDeletePriv())))
//				&& ((this.getCreatePriv() == castOther.getCreatePriv()) || (this.getCreatePriv() != null
//						&& castOther.getCreatePriv() != null && this.getCreatePriv().equals(castOther.getCreatePriv())))
//				&& ((this.getDropPriv() == castOther.getDropPriv()) || (this.getDropPriv() != null
//						&& castOther.getDropPriv() != null && this.getDropPriv().equals(castOther.getDropPriv())))
//				&& ((this.getReloadPriv() == castOther.getReloadPriv()) || (this.getReloadPriv() != null
//						&& castOther.getReloadPriv() != null && this.getReloadPriv().equals(castOther.getReloadPriv())))
//				&& ((this.getShutdownPriv() == castOther.getShutdownPriv())
//						|| (this.getShutdownPriv() != null && castOther.getShutdownPriv() != null
//								&& this.getShutdownPriv().equals(castOther.getShutdownPriv())))
//				&& ((this.getProcessPriv() == castOther.getProcessPriv())
//						|| (this.getProcessPriv() != null && castOther.getProcessPriv() != null
//								&& this.getProcessPriv().equals(castOther.getProcessPriv())))
//				&& ((this.getFilePriv() == castOther.getFilePriv()) || (this.getFilePriv() != null
//						&& castOther.getFilePriv() != null && this.getFilePriv().equals(castOther.getFilePriv())))
//				&& ((this.getGrantPriv() == castOther.getGrantPriv()) || (this.getGrantPriv() != null
//						&& castOther.getGrantPriv() != null && this.getGrantPriv().equals(castOther.getGrantPriv())))
//				&& ((this.getReferencesPriv() == castOther.getReferencesPriv())
//						|| (this.getReferencesPriv() != null && castOther.getReferencesPriv() != null
//								&& this.getReferencesPriv().equals(castOther.getReferencesPriv())))
//				&& ((this.getIndexPriv() == castOther.getIndexPriv()) || (this.getIndexPriv() != null
//						&& castOther.getIndexPriv() != null && this.getIndexPriv().equals(castOther.getIndexPriv())))
//				&& ((this.getAlterPriv() == castOther.getAlterPriv()) || (this.getAlterPriv() != null
//						&& castOther.getAlterPriv() != null && this.getAlterPriv().equals(castOther.getAlterPriv())))
//				&& ((this.getShowDbPriv() == castOther.getShowDbPriv()) || (this.getShowDbPriv() != null
//						&& castOther.getShowDbPriv() != null && this.getShowDbPriv().equals(castOther.getShowDbPriv())))
//				&& ((this.getSuperPriv() == castOther.getSuperPriv()) || (this.getSuperPriv() != null
//						&& castOther.getSuperPriv() != null && this.getSuperPriv().equals(castOther.getSuperPriv())))
//				&& ((this.getCreateTmpTablePriv() == castOther.getCreateTmpTablePriv())
//						|| (this.getCreateTmpTablePriv() != null && castOther.getCreateTmpTablePriv() != null
//								&& this.getCreateTmpTablePriv().equals(castOther.getCreateTmpTablePriv())))
//				&& ((this.getLockTablesPriv() == castOther.getLockTablesPriv())
//						|| (this.getLockTablesPriv() != null && castOther.getLockTablesPriv() != null
//								&& this.getLockTablesPriv().equals(castOther.getLockTablesPriv())))
//				&& ((this.getExecutePriv() == castOther.getExecutePriv())
//						|| (this.getExecutePriv() != null && castOther.getExecutePriv() != null
//								&& this.getExecutePriv().equals(castOther.getExecutePriv())))
//				&& ((this.getReplSlavePriv() == castOther.getReplSlavePriv())
//						|| (this.getReplSlavePriv() != null && castOther.getReplSlavePriv() != null
//								&& this.getReplSlavePriv().equals(castOther.getReplSlavePriv())))
//				&& ((this.getReplClientPriv() == castOther.getReplClientPriv())
//						|| (this.getReplClientPriv() != null && castOther.getReplClientPriv() != null
//								&& this.getReplClientPriv().equals(castOther.getReplClientPriv())))
//				&& ((this.getCreateViewPriv() == castOther.getCreateViewPriv())
//						|| (this.getCreateViewPriv() != null && castOther.getCreateViewPriv() != null
//								&& this.getCreateViewPriv().equals(castOther.getCreateViewPriv())))
//				&& ((this.getShowViewPriv() == castOther.getShowViewPriv())
//						|| (this.getShowViewPriv() != null && castOther.getShowViewPriv() != null
//								&& this.getShowViewPriv().equals(castOther.getShowViewPriv())))
//				&& ((this.getCreateRoutinePriv() == castOther.getCreateRoutinePriv())
//						|| (this.getCreateRoutinePriv() != null && castOther.getCreateRoutinePriv() != null
//								&& this.getCreateRoutinePriv().equals(castOther.getCreateRoutinePriv())))
//				&& ((this.getAlterRoutinePriv() == castOther.getAlterRoutinePriv())
//						|| (this.getAlterRoutinePriv() != null && castOther.getAlterRoutinePriv() != null
//								&& this.getAlterRoutinePriv().equals(castOther.getAlterRoutinePriv())))
//				&& ((this.getCreateUserPriv() == castOther.getCreateUserPriv())
//						|| (this.getCreateUserPriv() != null && castOther.getCreateUserPriv() != null
//								&& this.getCreateUserPriv().equals(castOther.getCreateUserPriv())))
//				&& ((this.getEventPriv() == castOther.getEventPriv()) || (this.getEventPriv() != null
//						&& castOther.getEventPriv() != null && this.getEventPriv().equals(castOther.getEventPriv())))
//				&& ((this.getTriggerPriv() == castOther.getTriggerPriv())
//						|| (this.getTriggerPriv() != null && castOther.getTriggerPriv() != null
//								&& this.getTriggerPriv().equals(castOther.getTriggerPriv())))
//				&& ((this.getCreateTablespacePriv() == castOther.getCreateTablespacePriv())
//						|| (this.getCreateTablespacePriv() != null && castOther.getCreateTablespacePriv() != null
//								&& this.getCreateTablespacePriv().equals(castOther.getCreateTablespacePriv())))
//				&& ((this.getDeleteHistoryPriv() == castOther.getDeleteHistoryPriv())
//						|| (this.getDeleteHistoryPriv() != null && castOther.getDeleteHistoryPriv() != null
//								&& this.getDeleteHistoryPriv().equals(castOther.getDeleteHistoryPriv())))
//				&& ((this.getSslType() == castOther.getSslType()) || (this.getSslType() != null
//						&& castOther.getSslType() != null && this.getSslType().equals(castOther.getSslType())))
//				&& ((this.getSslCipher() == castOther.getSslCipher()) || (this.getSslCipher() != null
//						&& castOther.getSslCipher() != null && this.getSslCipher().equals(castOther.getSslCipher())))
//				&& ((this.getX509Issuer() == castOther.getX509Issuer()) || (this.getX509Issuer() != null
//						&& castOther.getX509Issuer() != null && this.getX509Issuer().equals(castOther.getX509Issuer())))
//				&& ((this.getX509Subject() == castOther.getX509Subject())
//						|| (this.getX509Subject() != null && castOther.getX509Subject() != null
//								&& this.getX509Subject().equals(castOther.getX509Subject())))
//				&& (this.getMaxQuestions() == castOther.getMaxQuestions())
//				&& (this.getMaxUpdates() == castOther.getMaxUpdates())
//				&& (this.getMaxConnections() == castOther.getMaxConnections())
//				&& (this.getMaxUserConnections() == castOther.getMaxUserConnections())
//				&& ((this.getPlugin() == castOther.getPlugin()) || (this.getPlugin() != null
//						&& castOther.getPlugin() != null && this.getPlugin().equals(castOther.getPlugin())))
//				&& ((this.getAuthenticationString() == castOther.getAuthenticationString())
//						|| (this.getAuthenticationString() != null && castOther.getAuthenticationString() != null
//								&& this.getAuthenticationString().equals(castOther.getAuthenticationString())))
//				&& ((this.getPasswordExpired() == castOther.getPasswordExpired())
//						|| (this.getPasswordExpired() != null && castOther.getPasswordExpired() != null
//								&& this.getPasswordExpired().equals(castOther.getPasswordExpired())))
//				&& ((this.getIsRole() == castOther.getIsRole()) || (this.getIsRole() != null
//						&& castOther.getIsRole() != null && this.getIsRole().equals(castOther.getIsRole())))
//				&& ((this.getDefaultRole() == castOther.getDefaultRole())
//						|| (this.getDefaultRole() != null && castOther.getDefaultRole() != null
//								&& this.getDefaultRole().equals(castOther.getDefaultRole())))
//				&& ((this.getMaxStatementTime() == castOther.getMaxStatementTime())
//						|| (this.getMaxStatementTime() != null && castOther.getMaxStatementTime() != null
//								&& this.getMaxStatementTime().equals(castOther.getMaxStatementTime())));
//	}
//
//	public int hashCode() {
//		int result = 17;
//
//		result = 37 * result + (getHost() == null ? 0 : this.getHost().hashCode());
//		result = 37 * result + (getUser() == null ? 0 : this.getUser().hashCode());
//		result = 37 * result + (getPassword() == null ? 0 : this.getPassword().hashCode());
//		result = 37 * result + (getSelectPriv() == null ? 0 : this.getSelectPriv().hashCode());
//		result = 37 * result + (getInsertPriv() == null ? 0 : this.getInsertPriv().hashCode());
//		result = 37 * result + (getUpdatePriv() == null ? 0 : this.getUpdatePriv().hashCode());
//		result = 37 * result + (getDeletePriv() == null ? 0 : this.getDeletePriv().hashCode());
//		result = 37 * result + (getCreatePriv() == null ? 0 : this.getCreatePriv().hashCode());
//		result = 37 * result + (getDropPriv() == null ? 0 : this.getDropPriv().hashCode());
//		result = 37 * result + (getReloadPriv() == null ? 0 : this.getReloadPriv().hashCode());
//		result = 37 * result + (getShutdownPriv() == null ? 0 : this.getShutdownPriv().hashCode());
//		result = 37 * result + (getProcessPriv() == null ? 0 : this.getProcessPriv().hashCode());
//		result = 37 * result + (getFilePriv() == null ? 0 : this.getFilePriv().hashCode());
//		result = 37 * result + (getGrantPriv() == null ? 0 : this.getGrantPriv().hashCode());
//		result = 37 * result + (getReferencesPriv() == null ? 0 : this.getReferencesPriv().hashCode());
//		result = 37 * result + (getIndexPriv() == null ? 0 : this.getIndexPriv().hashCode());
//		result = 37 * result + (getAlterPriv() == null ? 0 : this.getAlterPriv().hashCode());
//		result = 37 * result + (getShowDbPriv() == null ? 0 : this.getShowDbPriv().hashCode());
//		result = 37 * result + (getSuperPriv() == null ? 0 : this.getSuperPriv().hashCode());
//		result = 37 * result + (getCreateTmpTablePriv() == null ? 0 : this.getCreateTmpTablePriv().hashCode());
//		result = 37 * result + (getLockTablesPriv() == null ? 0 : this.getLockTablesPriv().hashCode());
//		result = 37 * result + (getExecutePriv() == null ? 0 : this.getExecutePriv().hashCode());
//		result = 37 * result + (getReplSlavePriv() == null ? 0 : this.getReplSlavePriv().hashCode());
//		result = 37 * result + (getReplClientPriv() == null ? 0 : this.getReplClientPriv().hashCode());
//		result = 37 * result + (getCreateViewPriv() == null ? 0 : this.getCreateViewPriv().hashCode());
//		result = 37 * result + (getShowViewPriv() == null ? 0 : this.getShowViewPriv().hashCode());
//		result = 37 * result + (getCreateRoutinePriv() == null ? 0 : this.getCreateRoutinePriv().hashCode());
//		result = 37 * result + (getAlterRoutinePriv() == null ? 0 : this.getAlterRoutinePriv().hashCode());
//		result = 37 * result + (getCreateUserPriv() == null ? 0 : this.getCreateUserPriv().hashCode());
//		result = 37 * result + (getEventPriv() == null ? 0 : this.getEventPriv().hashCode());
//		result = 37 * result + (getTriggerPriv() == null ? 0 : this.getTriggerPriv().hashCode());
//		result = 37 * result + (getCreateTablespacePriv() == null ? 0 : this.getCreateTablespacePriv().hashCode());
//		result = 37 * result + (getDeleteHistoryPriv() == null ? 0 : this.getDeleteHistoryPriv().hashCode());
//		result = 37 * result + (getSslType() == null ? 0 : this.getSslType().hashCode());
//		result = 37 * result + (getSslCipher() == null ? 0 : this.getSslCipher().hashCode());
//		result = 37 * result + (getX509Issuer() == null ? 0 : this.getX509Issuer().hashCode());
//		result = 37 * result + (getX509Subject() == null ? 0 : this.getX509Subject().hashCode());
//		result = 37 * result + (int) this.getMaxQuestions();
//		result = 37 * result + (int) this.getMaxUpdates();
//		result = 37 * result + (int) this.getMaxConnections();
//		result = 37 * result + (int) this.getMaxUserConnections();
//		result = 37 * result + (getPlugin() == null ? 0 : this.getPlugin().hashCode());
//		result = 37 * result + (getAuthenticationString() == null ? 0 : this.getAuthenticationString().hashCode());
//		result = 37 * result + (getPasswordExpired() == null ? 0 : this.getPasswordExpired().hashCode());
//		result = 37 * result + (getIsRole() == null ? 0 : this.getIsRole().hashCode());
//		result = 37 * result + (getDefaultRole() == null ? 0 : this.getDefaultRole().hashCode());
//		result = 37 * result + (getMaxStatementTime() == null ? 0 : this.getMaxStatementTime().hashCode());
//		return result;
//	}
//
//}
