//package src.RevEngEntities;
//// Generated Mar 21, 2020 5:51:12 PM by Hibernate Tools 5.2.3.Final
//
//import javax.persistence.AttributeOverride;
//import javax.persistence.AttributeOverrides;
//import javax.persistence.Column;
//import javax.persistence.EmbeddedId;
//import javax.persistence.Entity;
//import javax.persistence.Table;
//
///**
// * User generated by hbm2java
// */
//@Entity
//@Table(name = "user", catalog = "mysql")
//public class User implements java.io.Serializable {
//
//	private UserId id;
//
//	public User() {
//	}
//
//	public User(UserId id) {
//		this.id = id;
//	}
//
//	@EmbeddedId
//
//	@AttributeOverrides({
//			@AttributeOverride(name = "host", column = @Column(name = "Host", nullable = false, length = 60)),
//			@AttributeOverride(name = "user", column = @Column(name = "User", nullable = false, length = 80)),
//			@AttributeOverride(name = "password", column = @Column(name = "Password")),
//			@AttributeOverride(name = "selectPriv", column = @Column(name = "Select_priv", length = 1)),
//			@AttributeOverride(name = "insertPriv", column = @Column(name = "Insert_priv", length = 1)),
//			@AttributeOverride(name = "updatePriv", column = @Column(name = "Update_priv", length = 1)),
//			@AttributeOverride(name = "deletePriv", column = @Column(name = "Delete_priv", length = 1)),
//			@AttributeOverride(name = "createPriv", column = @Column(name = "Create_priv", length = 1)),
//			@AttributeOverride(name = "dropPriv", column = @Column(name = "Drop_priv", length = 1)),
//			@AttributeOverride(name = "reloadPriv", column = @Column(name = "Reload_priv", length = 1)),
//			@AttributeOverride(name = "shutdownPriv", column = @Column(name = "Shutdown_priv", length = 1)),
//			@AttributeOverride(name = "processPriv", column = @Column(name = "Process_priv", length = 1)),
//			@AttributeOverride(name = "filePriv", column = @Column(name = "File_priv", length = 1)),
//			@AttributeOverride(name = "grantPriv", column = @Column(name = "Grant_priv", length = 1)),
//			@AttributeOverride(name = "referencesPriv", column = @Column(name = "References_priv", length = 1)),
//			@AttributeOverride(name = "indexPriv", column = @Column(name = "Index_priv", length = 1)),
//			@AttributeOverride(name = "alterPriv", column = @Column(name = "Alter_priv", length = 1)),
//			@AttributeOverride(name = "showDbPriv", column = @Column(name = "Show_db_priv", length = 1)),
//			@AttributeOverride(name = "superPriv", column = @Column(name = "Super_priv", length = 1)),
//			@AttributeOverride(name = "createTmpTablePriv", column = @Column(name = "Create_tmp_table_priv", length = 1)),
//			@AttributeOverride(name = "lockTablesPriv", column = @Column(name = "Lock_tables_priv", length = 1)),
//			@AttributeOverride(name = "executePriv", column = @Column(name = "Execute_priv", length = 1)),
//			@AttributeOverride(name = "replSlavePriv", column = @Column(name = "Repl_slave_priv", length = 1)),
//			@AttributeOverride(name = "replClientPriv", column = @Column(name = "Repl_client_priv", length = 1)),
//			@AttributeOverride(name = "createViewPriv", column = @Column(name = "Create_view_priv", length = 1)),
//			@AttributeOverride(name = "showViewPriv", column = @Column(name = "Show_view_priv", length = 1)),
//			@AttributeOverride(name = "createRoutinePriv", column = @Column(name = "Create_routine_priv", length = 1)),
//			@AttributeOverride(name = "alterRoutinePriv", column = @Column(name = "Alter_routine_priv", length = 1)),
//			@AttributeOverride(name = "createUserPriv", column = @Column(name = "Create_user_priv", length = 1)),
//			@AttributeOverride(name = "eventPriv", column = @Column(name = "Event_priv", length = 1)),
//			@AttributeOverride(name = "triggerPriv", column = @Column(name = "Trigger_priv", length = 1)),
//			@AttributeOverride(name = "createTablespacePriv", column = @Column(name = "Create_tablespace_priv", length = 1)),
//			@AttributeOverride(name = "deleteHistoryPriv", column = @Column(name = "Delete_history_priv", length = 1)),
//			@AttributeOverride(name = "sslType", column = @Column(name = "ssl_type", length = 9)),
//			@AttributeOverride(name = "sslCipher", column = @Column(name = "ssl_cipher", nullable = false)),
//			@AttributeOverride(name = "x509Issuer", column = @Column(name = "x509_issuer", nullable = false)),
//			@AttributeOverride(name = "x509Subject", column = @Column(name = "x509_subject", nullable = false)),
//			@AttributeOverride(name = "maxQuestions", column = @Column(name = "max_questions", nullable = false)),
//			@AttributeOverride(name = "maxUpdates", column = @Column(name = "max_updates", nullable = false)),
//			@AttributeOverride(name = "maxConnections", column = @Column(name = "max_connections", nullable = false)),
//			@AttributeOverride(name = "maxUserConnections", column = @Column(name = "max_user_connections", nullable = false)),
//			@AttributeOverride(name = "plugin", column = @Column(name = "plugin", nullable = false)),
//			@AttributeOverride(name = "authenticationString", column = @Column(name = "authentication_string", nullable = false)),
//			@AttributeOverride(name = "passwordExpired", column = @Column(name = "password_expired", nullable = false, length = 1)),
//			@AttributeOverride(name = "isRole", column = @Column(name = "is_role", length = 1)),
//			@AttributeOverride(name = "defaultRole", column = @Column(name = "default_role", nullable = false)),
//			@AttributeOverride(name = "maxStatementTime", column = @Column(name = "max_statement_time", nullable = false, precision = 12, scale = 6)) })
//	public UserId getId() {
//		return this.id;
//	}
//
//	public void setId(UserId id) {
//		this.id = id;
//	}
//
//}
