package Login.Registration.Model;
// Generated Mar 21, 2020 5:51:12 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tables generated by hbm2java
 */
@Entity
@Table(name = "TABLES")
public class Tables implements Serializable 
{
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private Set<TablesDet> tablesDets = new HashSet<TablesDet>(0);

	public Tables() 
	{
	}

	public Tables(String name) 
	{
		this.name = name;
	}

	public Tables(String name, Set<TablesDet> tablesDets) 
	{
		this.name = name;
		this.tablesDets = tablesDets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() 
	{
		return this.id;
	}

	public void setId(Integer id) 
	{
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() 
	{
		return this.name;
	}

	public void setName(String name) 
	{
		this.name = name;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "tables")
	public Set<TablesDet> getTablesDets() 
	{
		return this.tablesDets;
	}

	public void setTablesDets(Set<TablesDet> tablesDets) 
	{
		this.tablesDets = tablesDets;
	}

}
